In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_csv(r"C:\Users\jhank\Desktop\DA7\Projects\budget-impact-jupyternb-python\data\Metro_Budget_to_Actual_Expenses__FY2010_-_Present_.csv")

C:\Users\jhank\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3378: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
df.head(5)

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
0,10101,GSD General,1.0,Administrative,1101104.0,ADM County Retire Match,531702.0,Transfer Guaranteed Pension,3501900.0,3501900.00,...,3501900.0,3501900.00,3501900.0,3501900.00,3501900.0,3501900.00,3501900.0,3501900.00,3501900,3501900.00
1,10101,GSD General,1.0,Administrative,1101107.0,ADM Cnty Teach Retire Match,531702.0,Transfer Guaranteed Pension,6900400.0,6900400.00,...,6900400.0,6900400.00,6900400.0,6900400.00,6900400.0,6900400.00,6900400.0,6900400.00,6900400,6900400.00
2,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501174.0,Employer Group Health,28309600.0,29163668.82,...,49341100.0,48160249.84,49341100.0,50951314.92,51244600.0,51147253.42,53391800.0,51619782.62,55099100,52691663.82
3,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501175.0,Employer Dental Group,1823200.0,1831153.10,...,2741700.0,2660358.00,2741700.0,2871873.89,2986400.0,3045002.14,3063700.0,3128416.49,3063700,3201906.32
4,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501176.0,Employer Group Life,0.0,0.00,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00

In [6]:
df.tail(5)

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
30828,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501177.0,Employer Pension,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.859000e+01
30829,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501172.0,Employer OASDI,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-4.870000e+00
30830,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501173.0,Employer SSN Medical,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.990000e+00
30831,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501101.0,Regular Pay,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.506600e+02
30832,Grand Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.600288e+09,1.784957e+09,...,2.145225e+09,2.112964e+09,2.288721e+09,2.223645e+09,2.298126e+09,2.257203e+09,2.414639e+09,2.303677e+09,2455434200,3.031367e+09

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30833 entries, 0 to 30832
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fund                        30833 non-null  object
 1   Fund Description            30832 non-null  object
 2   Department                  30832 non-null  float64
 3   Department Description      30832 non-null  object
 4   Business Unit               30832 non-null  float64
 5   Business Unit Description   30832 non-null  object
 6   Object Account              30832 non-null  float64
 7   Object Account Description  30832 non-null  object
 8   FY2010 Budgeted Expenses    30833 non-null  float64
 9   FY2010 Actual Expenses      30833 non-null  float64
 10  FY2011 Budgeted Expenses    30833 non-null  float64
 11  FY2011 Actual Expenses      30833 non-null  float64
 12  FY2012 Budgeted Expenses    30833 non-null  float64
 13  FY2012 Actual Expenses      30833 non-null  float64
 14  FY2013 Budgeted Expenses    30833 non-null  float64
 15  FY2013 Actual Expenses      30833 non-null  float64
 16  FY2014 Budgeted Expenses    30833 non-null  float64
 17  FY2014 Actual Expenses      30833 non-null  float64
 18  FY2015 Budgeted Expenses    30833 non-null  float64
 19  FY2015 Actual Expenses      30833 non-null  float64
 20  FY2016 Budgeted Expenses    30833 non-null  float64
 21  FY2016 Actual Expenses      30833 non-null  float64
 22  FY2017 Budgeted Expenses    30833 non-null  float64
 23  FY2017 Actual Expenses      30833 non-null  float64
 24  FY2018 Budgeted Expenses    30833 non-null  float64
 25  FY2018 Actual Expenses      30833 non-null  float64
 26  FY2019 Budgeted Expenses    30833 non-null  float64
 27  FY2019 Actual Expenses      30833 non-null  float64
 28  FY2020 Budgeted Expenses    30833 non-null  float64
 29  FY2020 Actual Expenses      30833 non-null  float64
 30  FY2021 Budgeted Expenses    30833 non-null  int64
 31  FY2021 Actual Expenses      30833 non-null  float64
dtypes: float64(26), int64(1), object(5)
memory usage: 7.5+ MB

In [8]:
df['Department Description'].nunique()

52

In [9]:
dep_list = df['Department Description'].unique()

In [10]:
dep_list

array(['Administrative', 'Sheriff', 'Metropolitan Council',
       'Metropolitan Clerk', "Mayor's Office", 'Election Commission',
       'Law', 'Planning Commission', 'Human Resources',
       'Register of Deeds', 'General Services', 'Historical Commission',
       'Information Technology Service', 'Finance',
       'Assessor of Property', 'Trustee', 'County Clerk',
       'District Attorney', 'X-Medical Examiner', 'Public Defender',
       'Juvenile Court Clerk', 'Circuit Court Clerk',
       'Criminal Court Clerk', 'Clerk and Master - Chancery',
       'Juvenile Court', 'Police', 'General Sessions Court',
       'State Trial Courts', 'Justice Integration Services', 'Fire',
       'Codes Administration', 'Beer Board', 'Social Services',
       'Agricultural Extension', 'Soil and Water Conservation', 'Health',
       'Public Library', 'Parks', 'Arts Commission', 'Public Works',
       'MNPS', 'Human Relations Commission', 'X-Transportation Licensing',
       'Criminal Justice Planning', 'Internal Audit',
       'Office of Emergency Management', 'Office of Family Safety',
       'Community Oversight Board', 'Sports Authority',
       'Community Education Commission', 'Emergency Communication Center',
       'Debt Service', nan], dtype=object)

In [14]:
df2 = df[df['Department Description'] == 'Justice Integration Services']

In [15]:
df2

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
5998,10101,GSD General,29.0,Justice Integration Services,29160110.0,JIS ALOB IT Op & Maint Cost,503130.0,Computer Hardware <$10K,0.0,0.00,...,0.0,661.2,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
5999,10101,GSD General,29.0,Justice Integration Services,29160110.0,JIS ALOB IT Op & Maint Cost,502957.0,Telecmmnct'n Charge,0.0,10716.95,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6000,10101,GSD General,29.0,Justice Integration Services,29160110.0,JIS ALOB IT Op & Maint Cost,501172.0,Employer OASDI,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6001,10101,GSD General,29.0,Justice Integration Services,29160110.0,JIS ALOB IT Op & Maint Cost,501173.0,Employer SSN Medical,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6002,10101,GSD General,29.0,Justice Integration Services,29160110.0,JIS ALOB IT Op & Maint Cost,501181.0,FSA Pre-Tax Savings,0.0,0.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6179,10101,GSD General,29.0,Justice Integration Services,29162610.0,JIS Security Policy Enforce,501118.0,Admin Leave Disaster,0.0,289.11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6180,10101,GSD General,29.0,Justice Integration Services,29162610.0,JIS Security Policy Enforce,507450.0,Computer Hardware,0.0,33418.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6181,10101,GSD General,29.0,Justice Integration Services,29162710.0,JIS Info Request Responses,501172.0,Employer OASDI,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6182,10101,GSD General,29.0,Justice Integration Services,29162710.0,JIS Info Request Responses,501173.0,Employer SSN Medical,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
6183,10101,GSD General,29.0,Justice Integration Services,29162710.0,JIS Info Request Responses,501119.0,FY11 2% Adjustment,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0

In [17]:
df2['Business Unit Description'].unique()

array(['JIS ALOB IT Op & Maint Cost', 'JIS ALOB HR Employ Records',
       'JIS ALOB Exec Leader Key', 'JIS Workstation Config Key',
       'JIS ALOB Non Alloc Fin Trans', 'JIS Training Sessions Key',
       'JIS Project Plans Key', 'JIS Justice Appl Enhance Key',
       'JIS Test Plans Key', 'JIS Security Policy Enforce',
       'JIS Info Request Responses'], dtype=object)

In [18]:
df2['Object Account Description'].unique()

array(['Computer Hardware <$10K', "Telecmmnct'n Charge", 'Employer OASDI',
       'Employer SSN Medical', 'FSA Pre-Tax Savings',
       'Cafe Plan Pre-Tax Savings', 'Employee Local Travel/Park',
       'Other Rpr & Maint Srvc', 'Offc & Admin Supply',
       'FY11 2% Adjustment', 'Employer Group Health',
       'Employer Dental Group', 'Employer Group Life',
       'Rent Building & Land', 'Management Consultant',
       'Employer Pension', 'Employee Travel',
       'Allowance-Cell/Mobile Devices', 'Postage & Delivery Srvc',
       'Printing/Binding', 'Info Systems Charge', 'Computer Software',
       'Regular Pay', 'Leave Pay', 'Holiday Pay', 'Longevity',
       'YE Biweekly Sal/Fringe Accr', 'Pay Plan Improvement', 'Tuition',
       'Facilities Maint & Security', 'Software License',
       'FY12 1.5% Adjustment', 'Educational Supply', 'Paid Family Leave',
       'Surplus Property', 'Telephone & Telegraph',
       'Postal Service Charge', 'Small Equipment Supply',
       'Admin Leave Disaster', 'Bottled Water Service',
       'Computer Hardware', 'Transfer Indirect Admin',
       'Budget Adjustment', 'Employee Out-of-town Travel',
       "Advertising & Promot'n", 'Subscriptions', 'Credit Card Clearing',
       'Employee Air Travel', 'Membership Dues', 'Registration'],
      dtype=object)

In [20]:
df2.sum()

Fund                                                                    1878786
Fund Description              GSD GeneralGSD GeneralGSD GeneralGSD GeneralGS...
Department                                                               5394.0
Department Description        Justice Integration ServicesJustice Integratio...
Business Unit                                                      5424090800.0
Business Unit Description     JIS ALOB IT Op & Maint CostJIS ALOB IT Op & Ma...
Object Account                                                       93497368.0
Object Account Description    Computer Hardware <$10KTelecmmnct'n ChargeEmpl...
FY2010 Budgeted Expenses                                              2102600.0
FY2010 Actual Expenses                                               2033861.98
FY2011 Budgeted Expenses                                              2157600.0
FY2011 Actual Expenses                                                2098137.3
FY2012 Budgeted Expenses                                              2158300.0
FY2012 Actual Expenses                                               2134682.09
FY2013 Budgeted Expenses                                              2153000.0
FY2013 Actual Expenses                                               2142640.37
FY2014 Budgeted Expenses                                              2214200.0
FY2014 Actual Expenses                                               2196485.28
FY2015 Budgeted Expenses                                              2251700.0
FY2015 Actual Expenses                                               2114404.32
FY2016 Budgeted Expenses                                              2471000.0
FY2016 Actual Expenses                                               2359004.12
FY2017 Budgeted Expenses                                              2561800.0
FY2017 Actual Expenses                                               2523884.71
FY2018 Budgeted Expenses                                              2779500.0
FY2018 Actual Expenses                                               2665264.44
FY2019 Budgeted Expenses                                              2889900.0
FY2019 Actual Expenses                                               2889864.67
FY2020 Budgeted Expenses                                              2767200.0
FY2020 Actual Expenses                                               2751584.01
FY2021 Budgeted Expenses                                                2907300
FY2021 Actual Expenses                                               2882987.72
dtype: object