In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv(r"C:\Users\jhank\Desktop\DA7\Projects\budget-impact-jupyternb-python\data\Metro_Budget_to_Actual_Expenses__FY2010_-_Present_.csv")

C:\Users\jhank\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3378: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.head(5)

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
0,10101,GSD General,1.0,Administrative,1101104.0,ADM County Retire Match,531702.0,Transfer Guaranteed Pension,3501900.0,3501900.00,...,3501900.0,3501900.00,3501900.0,3501900.00,3501900.0,3501900.00,3501900.0,3501900.00,3501900,3501900.00
1,10101,GSD General,1.0,Administrative,1101107.0,ADM Cnty Teach Retire Match,531702.0,Transfer Guaranteed Pension,6900400.0,6900400.00,...,6900400.0,6900400.00,6900400.0,6900400.00,6900400.0,6900400.00,6900400.0,6900400.00,6900400,6900400.00
2,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501174.0,Employer Group Health,28309600.0,29163668.82,...,49341100.0,48160249.84,49341100.0,50951314.92,51244600.0,51147253.42,53391800.0,51619782.62,55099100,52691663.82
3,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501175.0,Employer Dental Group,1823200.0,1831153.10,...,2741700.0,2660358.00,2741700.0,2871873.89,2986400.0,3045002.14,3063700.0,3128416.49,3063700,3201906.32
4,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501176.0,Employer Group Life,0.0,0.00,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00

In [5]:
df.tail(5)

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
30828,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501177.0,Employer Pension,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.859000e+01
30829,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501172.0,Employer OASDI,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-4.870000e+00
30830,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501173.0,Employer SSN Medical,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.990000e+00
30831,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501101.0,Regular Pay,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.506600e+02
30832,Grand Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.600288e+09,1.784957e+09,...,2.145225e+09,2.112964e+09,2.288721e+09,2.223645e+09,2.298126e+09,2.257203e+09,2.414639e+09,2.303677e+09,2455434200,3.031367e+09

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30833 entries, 0 to 30832
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fund                        30833 non-null  object
 1   Fund Description            30832 non-null  object
 2   Department                  30832 non-null  float64
 3   Department Description      30832 non-null  object
 4   Business Unit               30832 non-null  float64
 5   Business Unit Description   30832 non-null  object
 6   Object Account              30832 non-null  float64
 7   Object Account Description  30832 non-null  object
 8   FY2010 Budgeted Expenses    30833 non-null  float64
 9   FY2010 Actual Expenses      30833 non-null  float64
 10  FY2011 Budgeted Expenses    30833 non-null  float64
 11  FY2011 Actual Expenses      30833 non-null  float64
 12  FY2012 Budgeted Expenses    30833 non-null  float64
 13  FY2012 Actual Expenses      30833 non-null  float64
 14  FY2013 Budgeted Expenses    30833 non-null  float64
 15  FY2013 Actual Expenses      30833 non-null  float64
 16  FY2014 Budgeted Expenses    30833 non-null  float64
 17  FY2014 Actual Expenses      30833 non-null  float64
 18  FY2015 Budgeted Expenses    30833 non-null  float64
 19  FY2015 Actual Expenses      30833 non-null  float64
 20  FY2016 Budgeted Expenses    30833 non-null  float64
 21  FY2016 Actual Expenses      30833 non-null  float64
 22  FY2017 Budgeted Expenses    30833 non-null  float64
 23  FY2017 Actual Expenses      30833 non-null  float64
 24  FY2018 Budgeted Expenses    30833 non-null  float64
 25  FY2018 Actual Expenses      30833 non-null  float64
 26  FY2019 Budgeted Expenses    30833 non-null  float64
 27  FY2019 Actual Expenses      30833 non-null  float64
 28  FY2020 Budgeted Expenses    30833 non-null  float64
 29  FY2020 Actual Expenses      30833 non-null  float64
 30  FY2021 Budgeted Expenses    30833 non-null  int64
 31  FY2021 Actual Expenses      30833 non-null  float64
dtypes: float64(26), int64(1), object(5)
memory usage: 7.5+ MB

In [7]:
df['Department Description'].nunique()

52

In [8]:
dep_list = df['Department Description'].unique()

In [9]:
dep_list

array(['Administrative', 'Sheriff', 'Metropolitan Council',
       'Metropolitan Clerk', "Mayor's Office", 'Election Commission',
       'Law', 'Planning Commission', 'Human Resources',
       'Register of Deeds', 'General Services', 'Historical Commission',
       'Information Technology Service', 'Finance',
       'Assessor of Property', 'Trustee', 'County Clerk',
       'District Attorney', 'X-Medical Examiner', 'Public Defender',
       'Juvenile Court Clerk', 'Circuit Court Clerk',
       'Criminal Court Clerk', 'Clerk and Master - Chancery',
       'Juvenile Court', 'Police', 'General Sessions Court',
       'State Trial Courts', 'Justice Integration Services', 'Fire',
       'Codes Administration', 'Beer Board', 'Social Services',
       'Agricultural Extension', 'Soil and Water Conservation', 'Health',
       'Public Library', 'Parks', 'Arts Commission', 'Public Works',
       'MNPS', 'Human Relations Commission', 'X-Transportation Licensing',
       'Criminal Justice Planning', 'Internal Audit',
       'Office of Emergency Management', 'Office of Family Safety',
       'Community Oversight Board', 'Sports Authority',
       'Community Education Commission', 'Emergency Communication Center',
       'Debt Service', nan], dtype=object)

In [10]:
df2 = df[df['Department Description'] == 'Law']

In [11]:
df2

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
1160,10101,GSD General,6.0,Law,6110010.0,LAW Contracts All Services,501174.0,Employer Group Health,15600.0,7926.72,...,5800.0,6205.96,5800.0,7242.11,5800.0,6349.50,5800.0,5754.64,5800,5923.08
1161,10101,GSD General,6.0,Law,6110010.0,LAW Contracts All Services,501175.0,Employer Dental Group,500.0,293.23,...,500.0,155.97,500.0,214.39,500.0,192.65,500.0,349.58,500,170.58
1162,10101,GSD General,6.0,Law,6110010.0,LAW Contracts All Services,501176.0,Employer Group Life,600.0,129.64,...,200.0,103.86,200.0,95.07,200.0,89.82,200.0,81.13,200,79.63
1163,10101,GSD General,6.0,Law,6110010.0,LAW Contracts All Services,505231.0,Rent Building & Land,14000.0,14000.00,...,14000.0,14000.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00
1164,10101,GSD General,6.0,Law,6110010.0,LAW Contracts All Services,501177.0,Employer Pension,20400.0,9237.31,...,4500.0,7136.88,8900.0,7152.31,7700.0,7136.60,7900.0,7469.09,7900,7415.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1397,10101,GSD General,6.0,Law,6110610.0,LAW Insurance All Services,501118.0,Admin Leave Disaster,0.0,72.12,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00
1398,10101,GSD General,6.0,Law,6111000.0,LAWALOB Non-Alloc'd Fin Trans,501174.0,Employer Group Health,0.0,0.00,...,10900.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00
1399,10101,GSD General,6.0,Law,6111000.0,LAWALOB Non-Alloc'd Fin Trans,501177.0,Employer Pension,0.0,0.00,...,0.0,0.00,0.0,0.00,11800.0,0.00,0.0,0.00,0,0.00
1400,10101,GSD General,6.0,Law,6111000.0,LAWALOB Non-Alloc'd Fin Trans,501112.0,Pay Plan Improvement,0.0,0.00,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00
1401,10101,GSD General,6.0,Law,6111000.0,LAWALOB Non-Alloc'd Fin Trans,590002.0,Budget Adjustment,0.0,0.00,...,0.0,0.00,0.0,0.00,-161100.0,0.00,-161100.0,0.00,0,0.00

In [12]:
df2['Business Unit Description'].unique()

array(['LAW Contracts All Services', 'LAW Client Adv/Supp All Servic',
       'LAW Legislation All Services', 'LAW Lit/Admin Hear All Service',
       'LAW Claims All Services', 'LAW Insurance All Services',
       "LAWALOB Non-Alloc'd Fin Trans"], dtype=object)

In [13]:
df2['Object Account Description'].unique()

array(['Employer Group Health', 'Employer Dental Group',
       'Employer Group Life', 'Rent Building & Land', 'Employer Pension',
       "Telecmmnct'n Charge", 'Employer OASDI', 'Employer SSN Medical',
       'FSA Pre-Tax Savings', 'Cafe Plan Pre-Tax Savings',
       'Employee Local Travel/Park', 'Allowance-Cell/Mobile Devices',
       'Printing/Binding', 'Membership Dues', 'Info Systems Charge',
       'Offc & Admin Supply', 'Computer Software', 'Rent Equipment',
       'Regular Pay', 'Leave Pay', 'Holiday Pay', 'Longevity',
       'YE Biweekly Sal/Fringe Accr', 'Host & Hostess',
       'Facilities Maint & Security', 'FY11 2% Adjustment',
       'Books/Magazines/Periodicals', 'Cable Television', 'Subscriptions',
       'Injured on Duty Pay', 'Paid Family Leave', 'Internet Services',
       'Cell Phone Service', 'Postal Service Charge',
       'Professional Privilege Tax', 'Admin Leave Disaster',
       'Admin Leave COVID-19', 'Bottled Water Service',
       'Management Consultant', 'Computer Hardware <$10K',
       'Legal Services', 'Employee Out-of-town Travel',
       'Employee Air Travel', 'Postage & Delivery Srvc',
       "Advertising & Promot'n", 'Other Rpr & Maint Srvc', 'Registration',
       'Pre-Employment Checks', 'FY12 1.5% Adjustment', 'Notary',
       'Surplus Property', 'Credit Card Clearing', 'Retirement Incentive',
       'Office Equip Maintain Srvc', 'Fleet Management', 'Medical Supply',
       'NSF Checks', 'Pay Plan Improvement', 'Budget Adjustment'],
      dtype=object)

In [14]:
df2.sum()

Fund                                                                    2434341
Fund Description              GSD GeneralGSD GeneralGSD GeneralGSD GeneralGS...
Department                                                               1446.0
Department Description        LawLawLawLawLawLawLawLawLawLawLawLawLawLawLawL...
Business Unit                                                      1472576870.0
Business Unit Description     LAW Contracts All ServicesLAW Contracts All Se...
Object Account                                                      121130332.0
Object Account Description    Employer Group HealthEmployer Dental GroupEmpl...
FY2010 Budgeted Expenses                                              5341000.0
FY2010 Actual Expenses                                               5214462.27
FY2011 Budgeted Expenses                                              5371000.0
FY2011 Actual Expenses                                               5330272.26
FY2012 Budgeted Expenses                                              5241300.0
FY2012 Actual Expenses                                                5186839.0
FY2013 Budgeted Expenses                                              5328200.0
FY2013 Actual Expenses                                               5296431.21
FY2014 Budgeted Expenses                                              5383100.0
FY2014 Actual Expenses                                               5314416.84
FY2015 Budgeted Expenses                                              5259100.0
FY2015 Actual Expenses                                               5227087.93
FY2016 Budgeted Expenses                                              5612500.0
FY2016 Actual Expenses                                               5531401.41
FY2017 Budgeted Expenses                                              5999400.0
FY2017 Actual Expenses                                               5925637.72
FY2018 Budgeted Expenses                                              6195500.0
FY2018 Actual Expenses                                               6084985.47
FY2019 Budgeted Expenses                                              6157400.0
FY2019 Actual Expenses                                               5987572.02
FY2020 Budgeted Expenses                                              6427600.0
FY2020 Actual Expenses                                               6126051.04
FY2021 Budgeted Expenses                                                6445600
FY2021 Actual Expenses                                               6026298.08
dtype: object