In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv(r"C:\Users\jhank\Desktop\DA7\Projects\budget-impact-jupyternb-python\data\Metro_Budget_to_Actual_Expenses__FY2010_-_Present_.csv")

C:\Users\jhank\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3378: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.head(5)

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
0,10101,GSD General,1.0,Administrative,1101104.0,ADM County Retire Match,531702.0,Transfer Guaranteed Pension,3501900.0,3501900.00,...,3501900.0,3501900.00,3501900.0,3501900.00,3501900.0,3501900.00,3501900.0,3501900.00,3501900,3501900.00
1,10101,GSD General,1.0,Administrative,1101107.0,ADM Cnty Teach Retire Match,531702.0,Transfer Guaranteed Pension,6900400.0,6900400.00,...,6900400.0,6900400.00,6900400.0,6900400.00,6900400.0,6900400.00,6900400.0,6900400.00,6900400,6900400.00
2,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501174.0,Employer Group Health,28309600.0,29163668.82,...,49341100.0,48160249.84,49341100.0,50951314.92,51244600.0,51147253.42,53391800.0,51619782.62,55099100,52691663.82
3,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501175.0,Employer Dental Group,1823200.0,1831153.10,...,2741700.0,2660358.00,2741700.0,2871873.89,2986400.0,3045002.14,3063700.0,3128416.49,3063700,3201906.32
4,10101,GSD General,1.0,Administrative,1101109.0,ADM Health Insurance Match,501176.0,Employer Group Life,0.0,0.00,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00

In [5]:
df.tail(5)

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
30828,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501177.0,Employer Pension,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.859000e+01
30829,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501172.0,Employer OASDI,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-4.870000e+00
30830,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501173.0,Employer SSN Medical,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.990000e+00
30831,35131,MNPS General Purpose,80.0,MNPS,80902020.0,MNPS COVID-19,501101.0,Regular Pay,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0,-1.506600e+02
30832,Grand Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.600288e+09,1.784957e+09,...,2.145225e+09,2.112964e+09,2.288721e+09,2.223645e+09,2.298126e+09,2.257203e+09,2.414639e+09,2.303677e+09,2455434200,3.031367e+09

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30833 entries, 0 to 30832
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fund                        30833 non-null  object
 1   Fund Description            30832 non-null  object
 2   Department                  30832 non-null  float64
 3   Department Description      30832 non-null  object
 4   Business Unit               30832 non-null  float64
 5   Business Unit Description   30832 non-null  object
 6   Object Account              30832 non-null  float64
 7   Object Account Description  30832 non-null  object
 8   FY2010 Budgeted Expenses    30833 non-null  float64
 9   FY2010 Actual Expenses      30833 non-null  float64
 10  FY2011 Budgeted Expenses    30833 non-null  float64
 11  FY2011 Actual Expenses      30833 non-null  float64
 12  FY2012 Budgeted Expenses    30833 non-null  float64
 13  FY2012 Actual Expenses      30833 non-null  float64
 14  FY2013 Budgeted Expenses    30833 non-null  float64
 15  FY2013 Actual Expenses      30833 non-null  float64
 16  FY2014 Budgeted Expenses    30833 non-null  float64
 17  FY2014 Actual Expenses      30833 non-null  float64
 18  FY2015 Budgeted Expenses    30833 non-null  float64
 19  FY2015 Actual Expenses      30833 non-null  float64
 20  FY2016 Budgeted Expenses    30833 non-null  float64
 21  FY2016 Actual Expenses      30833 non-null  float64
 22  FY2017 Budgeted Expenses    30833 non-null  float64
 23  FY2017 Actual Expenses      30833 non-null  float64
 24  FY2018 Budgeted Expenses    30833 non-null  float64
 25  FY2018 Actual Expenses      30833 non-null  float64
 26  FY2019 Budgeted Expenses    30833 non-null  float64
 27  FY2019 Actual Expenses      30833 non-null  float64
 28  FY2020 Budgeted Expenses    30833 non-null  float64
 29  FY2020 Actual Expenses      30833 non-null  float64
 30  FY2021 Budgeted Expenses    30833 non-null  int64
 31  FY2021 Actual Expenses      30833 non-null  float64
dtypes: float64(26), int64(1), object(5)
memory usage: 7.5+ MB

In [7]:
df['Department Description'].nunique()

52

In [8]:
dep_list = df['Department Description'].unique()

In [9]:
dep_list

array(['Administrative', 'Sheriff', 'Metropolitan Council',
       'Metropolitan Clerk', "Mayor's Office", 'Election Commission',
       'Law', 'Planning Commission', 'Human Resources',
       'Register of Deeds', 'General Services', 'Historical Commission',
       'Information Technology Service', 'Finance',
       'Assessor of Property', 'Trustee', 'County Clerk',
       'District Attorney', 'X-Medical Examiner', 'Public Defender',
       'Juvenile Court Clerk', 'Circuit Court Clerk',
       'Criminal Court Clerk', 'Clerk and Master - Chancery',
       'Juvenile Court', 'Police', 'General Sessions Court',
       'State Trial Courts', 'Justice Integration Services', 'Fire',
       'Codes Administration', 'Beer Board', 'Social Services',
       'Agricultural Extension', 'Soil and Water Conservation', 'Health',
       'Public Library', 'Parks', 'Arts Commission', 'Public Works',
       'MNPS', 'Human Relations Commission', 'X-Transportation Licensing',
       'Criminal Justice Planning', 'Internal Audit',
       'Office of Emergency Management', 'Office of Family Safety',
       'Community Oversight Board', 'Sports Authority',
       'Community Education Commission', 'Emergency Communication Center',
       'Debt Service', nan], dtype=object)

In [10]:
df2 = df[df['Department Description'] == 'Public Works']

In [11]:
df2

,Fund,Fund Description,Department,Department Description,Business Unit,Business Unit Description,Object Account,Object Account Description,FY2010 Budgeted Expenses,FY2010 Actual Expenses,...,FY2017 Budgeted Expenses,FY2017 Actual Expenses,FY2018 Budgeted Expenses,FY2018 Actual Expenses,FY2019 Budgeted Expenses,FY2019 Actual Expenses,FY2020 Budgeted Expenses,FY2020 Actual Expenses,FY2021 Budgeted Expenses,FY2021 Actual Expenses
18769,10101,GSD General,42.0,Public Works,42145210.0,PW TL Enforcement,503804.0,Auto Repair Parts,0.0,0.00,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00
18911,10101,GSD General,42.0,Public Works,42141110.0,PW GSD Developer Services,501174.0,Employer Group Health,92500.0,91671.00,...,93600.0,107869.21,117500.0,98370.00,110200.0,96816.00,98200.0,103539.00,122200,107811.83
18912,10101,GSD General,42.0,Public Works,42141110.0,PW GSD Developer Services,501175.0,Employer Dental Group,3000.0,3097.14,...,3400.0,3351.14,3700.0,3301.62,4000.0,3428.74,3700.0,7774.17,4200,3314.97
18913,10101,GSD General,42.0,Public Works,42141110.0,PW GSD Developer Services,501176.0,Employer Group Life,1500.0,1505.25,...,4000.0,1909.19,4100.0,1750.15,3700.0,1727.43,4000.0,1814.37,2000,1759.70
18914,10101,GSD General,42.0,Public Works,42141110.0,PW GSD Developer Services,502339.0,Recording,0.0,0.00,...,0.0,20.00,0.0,0.00,0.0,0.00,0.0,0.00,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21189,18301,USD General,42.0,Public Works,42197110.0,PW USD Administration,502102.0,Water,0.0,0.00,...,13000.0,15174.96,13000.0,17923.38,13000.0,16792.48,13000.0,18179.76,13000,13200.43
21190,18301,USD General,42.0,Public Works,42197110.0,PW USD Administration,502983.0,Surplus Property,2700.0,2700.00,...,6400.0,6400.00,6600.0,6600.00,6500.0,6500.00,6800.0,6800.00,7900,7900.00
21191,18301,USD General,42.0,Public Works,42197110.0,PW USD Administration,502303.0,Refuse Disposal,39000.0,62625.86,...,26000.0,0.00,26000.0,0.00,26000.0,0.00,26000.0,0.00,26000,0.00
21192,18301,USD General,42.0,Public Works,42197110.0,PW USD Administration,502977.0,Fleet Management,93100.0,93100.00,...,141600.0,141600.00,364000.0,329763.12,155300.0,155300.00,122100.0,122100.00,204300,204300.00
21193,18301,USD General,42.0,Public Works,42197110.0,PW USD Administration,531120.0,Transfer Solid Waste,9833900.0,9833900.00,...,14738400.0,14738400.00,14494800.0,14494800.00,14606300.0,14606300.00,15704800.0,15704800.00,20480900,20480900.00

In [12]:
df2['Business Unit Description'].unique()

array(['PW TL Enforcement', 'PW GSD Developer Services',
       'PW GSD Traffic Engineering', 'PW GSD Right of Way Permits',
       'PW GSD Park Spaces Off Street', 'PW GSD Park Spaces On Street',
       'PW GSD Street Construction', 'PW GSD Sidewalk Construction',
       'PW GSD ITS Construction', 'PW GSD Roadway Maintenance',
       'PW GSD Film and Special Events', 'PW GSD Emergency Response',
       'PW GSD Traffic Signal Maint', 'PW GSD Alley Maintenance',
       'PW GSD Traffic Sign & Marking', 'PW GSD Brush Collection',
       'PW GSD Cust Serv Resp & Supp', 'PW GSD Compost Program',
       'PW TL Transportation Licensing', 'PW TL Inspection',
       'PW TL Permitting', 'PW GSD Transport Systems Development',
       'PW GSD Active Transportation', "PW ALOB Non Alloc'd Fin Tran",
       'PW GSD Non Allocated Transfers', 'PW NonPayrollExp Clearing',
       'PW GSD Administration', 'PW USD Roadway All Other',
       "PW USD ALOB Non Alloc'd Fin", 'PW USD Administration'],
      dtype=object)

In [13]:
df2['Object Account Description'].unique()

array(['Auto Repair Parts', 'Employer Group Health',
       'Employer Dental Group', 'Employer Group Life', 'Recording',
       'Employer Pension', 'Computer Hardware <$10K',
       "Telecmmnct'n Charge", 'Employer OASDI', 'Employer SSN Medical',
       'FSA Pre-Tax Savings', 'Cafe Plan Pre-Tax Savings',
       'Employee Out-of-town Travel', 'Employee Air Travel',
       'Employee Local Travel/Park', 'Allowance-Cell/Mobile Devices',
       'Postage & Delivery Srvc', 'Printing/Binding', 'Membership Dues',
       'Other Rpr & Maint Srvc', 'Info Systems Charge',
       'Offc & Admin Supply', 'Computer Software', 'Regular Pay',
       'Leave Pay', 'Holiday Pay', 'Overtime Pay', 'Longevity',
       'YE Biweekly Sal/Fringe Accr', 'Engineering Srvc',
       'Personal Use Supply', 'Registration', 'Pre-Employment Checks',
       'Host & Hostess', 'Repair & Maint Supply', 'Software License',
       'FY11 2% Adjustment', 'FY12 1.5% Adjustment',
       'Books/Magazines/Periodicals', 'Out of Class Pay', 'Subscriptions',
       'Furniture/Fixtures<$10K', 'Uniforms/Work Related Items',
       'Safety Shoes', 'Paid Family Leave', 'Other License & Fees',
       'Cell Phone Service', 'Professional Privilege Tax',
       'Retirement Incentive', 'Small Equipment Supply',
       'Admin Leave Disaster', 'Temporary Service', 'Fleet Management',
       'HHold & Jnitr Supply', 'Admin Leave COVID-19', 'Auto Fuel',
       'Signs', 'Medical Supply', 'Safety Supply', 'Lock & Key Service',
       'Plumbing/HVAC Maintain Srvc', 'Paint', 'Auto Supply',
       'Admin Leave Emergency Closures', 'Uniforms - Allowance',
       'Paint Supply', "Advertising & Promot'n", 'Injured on Duty Pay',
       'Office Equip Maintain Srvc', 'Construction Supply',
       'Fingerprinting', 'Rent Equipment', 'Other Special Pay',
       'Food & Ice', 'Uniform Cleaning Service', 'Facilities Management',
       'TBI Background Check Service', 'OFM Direct Billed Charges',
       'IOD-Light Duty', 'IOD-CS 90 Percent', 'Electronic Parts/Supply',
       'Auto Oil/Lubricants', 'Stone/Gravel/Sand', 'Cement Products',
       'Metal Pipes/Fittings', 'Office Equipment < $10K', 'Electric',
       'Educational Supply', 'Internet Services', 'Telephone & Telegraph',
       'Printing Supply', 'Credit Card Clearing', 'Refuse Disposal',
       'Radio Shop Charge', 'Drug Test Fee', 'Shift Differential Pay',
       'Machinery & Equipment', 'Pest Control Srvc',
       'Computer Communication Servs', 'Building Improvements',
       'IOD-CS 100 Percent', 'Hazard Waste Disposal',
       'Lumber/Wood Products', 'Ag & Animal Supply', 'Asphalt Mix',
       'Ready Mix Concrete', 'Dirt/Straw/Seed', 'Concrete Pipes/Fittings',
       'Sweeping', 'Roads & Streets- Repairs', 'Motor Pool Charge',
       'Pay Plan Improvement', 'Facilities Maint & Security',
       'Postal Service Charge', 'Vehicle Washing',
       'x-Rename for Use Later', 'Management Consultant',
       'Surplus Property', 'Other Purchased Srvc', 'Stormwater',
       'Budget Adjustment', 'Water', 'NSF Checks', 'Transfer Operational',
       'Rent Building & Land', 'Gas', 'Employee Travel',
       'Building Maintenance Srvc', 'Tuition', 'Security Services',
       'Interest Expense MIP', 'Medical Services', 'Cable Television',
       'Devlop/Framing/Artwork', 'Janitorial Srvc', 'Alarm Permits',
       'Merchant Fees', 'Laundry Services', 'Educational Service',
       'Electrical Repair Service', 'Electrical Supply',
       'Boiler Inspection', 'Bank Fees', 'Health Services',
       'Transfer Solid Waste'], dtype=object)

In [14]:
df2.sum()

Fund                          1010110101101011010110101101011010110101101011...
Fund Description              GSD GeneralGSD GeneralGSD GeneralGSD GeneralGS...
Department                                                              46074.0
Department Description        Public WorksPublic WorksPublic WorksPublic Wor...
Business Unit                                                     46235414540.0
Business Unit Description     PW TL EnforcementPW GSD Developer ServicesPW G...
Object Account                                                      551229373.0
Object Account Description    Auto Repair PartsEmployer Group HealthEmployer...
FY2010 Budgeted Expenses                                             45197700.0
FY2010 Actual Expenses                                               44593270.3
FY2011 Budgeted Expenses                                             48697000.0
FY2011 Actual Expenses                                              48339655.74
FY2012 Budgeted Expenses                                             49000900.0
FY2012 Actual Expenses                                              48206548.62
FY2013 Budgeted Expenses                                             47647000.0
FY2013 Actual Expenses                                              46664704.85
FY2014 Budgeted Expenses                                             47094200.0
FY2014 Actual Expenses                                              46548678.02
FY2015 Budgeted Expenses                                             46183200.0
FY2015 Actual Expenses                                              45921252.29
FY2016 Budgeted Expenses                                             51065000.0
FY2016 Actual Expenses                                              49728232.48
FY2017 Budgeted Expenses                                             55301600.0
FY2017 Actual Expenses                                              54589584.05
FY2018 Budgeted Expenses                                             56792200.0
FY2018 Actual Expenses                                              54594953.96
FY2019 Budgeted Expenses                                             56027100.0
FY2019 Actual Expenses                                              55386549.66
FY2020 Budgeted Expenses                                             58198400.0
FY2020 Actual Expenses                                              57796576.98
FY2021 Budgeted Expenses                                               65129900
FY2021 Actual Expenses                                              63379916.56
dtype: object